angular.module("shareApp_admin")
.controller("dashboard_controller",function($rootScope,$scope,$http){
	$http.get('user/count_by_sex.json').success(
			function(response){
				$scope.userSexCountData=response.userSexCountData;
				//性别分布
			      var chart = iChart.create({
			            render:"ichart-sex",
			            width:400,
			            height:300,
			            background_color:"rgb(238,238,238)",
			            gradient:false,
			            color_factor:0.2,
			            border:{
			                  color:"BCBCBC",
			                  width:0
			            },
			            align:"center",
			            offsetx:0,
			            offsety:0,
			            sub_option:{
			                  border:{
			                        color:"#BCBCBC",
			                        width:0
			                  },
			                  label:{
			                        fontweight:500,
			                        fontsize:11,
			                        color:"#4572a7",
			                        sign:"square",
			                        sign_size:12,
			                        border:{
			                              color:"#BCBCBC",
			                              width:0
			                        },
			                        background_color:"rgb(238,238,238)"
			                  }
			            },
			            shadow:true,
			            shadow_color:"#666666",
			            shadow_blur:2,
			            showpercent:true,
			            column_width:"70%",
			            bar_height:"70%",
			            radius:"100%",
			            title:{
			                  text:"男女比例分布",
			                  color:"#111111",
			                  fontsize:20,
			                  font:"微软雅黑",
			                  textAlign:"center",
			                  height:30,
			                  offsetx:0,
			                  offsety:0
			            },
			            subtitle:{
			                  text:"",
			                  color:"#111111",
			                  fontsize:16,
			                  font:"微软雅黑",
			                  textAlign:"center",
			                  height:20,
			                  offsetx:0,
			                  offsety:0
			            },
			            footnote:{
			                  text:"",
			                  color:"#111111",
			                  fontsize:12,
			                  font:"微软雅黑",
			                  textAlign:"right",
			                  height:20,
			                  offsetx:0,
			                  offsety:0
			            },
			            legend:{
			                  enable:false,
			                  background_color:"rgb(238,238,238)",
			                  color:"#333333",
			                  fontsize:12,
			                  border:{
			                        color:"#BCBCBC",
			                        width:0
			                  },
			                  column:1,
			                  align:"right",
			                  valign:"center",
			                  offsetx:0,
			                  offsety:0
			            },
			            coordinate:{
			                  width:"80%",
			                  height:"84%",
			                  background_color:"#ffffff",
			                  axis:{
			                        color:"#a5acb8",
			                        width:[1,"",1,""]
			                  },
			                  grid_color:"#d9d9d9",
			                  label:{
			                        fontweight:500,
			                        color:"#666666",
			                        fontsize:11
			                  }
			            },
			            label:{
			                  fontweight:500,
			                  color:"#666666",
			                  fontsize:11
			            },
			            type:"pie2d",
			            data:$scope.userSexCountData
			      });
			      chart.draw();
		}
	);
	
	$http.get('stuff/count_by_type.json').success(
			function(response){
				$scope.stuffTypeCountData=response.stuffTypeCountData;
				 //资源类型比例分布
			      var chart = iChart.create({
			            render:"ichart-stuffType",
			            width:430,
			            height:300,
			            background_color:"rgb(238,238,238)",
			            gradient:false,
			            color_factor:0.2,
			            border:{
			                  color:"BCBCBC",
			                  width:0
			            },
			            align:"center",
			            offsetx:0,
			            offsety:0,
			            sub_option:{
			                  border:{
			                        color:"#BCBCBC",
			                        width:0
			                  },
			                  label:{
			                        fontweight:500,
			                        fontsize:11,
			                        color:"#4572a7",
			                        sign:"square",
			                        sign_size:12,
			                        border:{
			                              color:"#BCBCBC",
			                              width:0
			                        },
			                        background_color:"rgb(238,238,238)"
			                  }
			            },
			            shadow:true,
			            shadow_color:"#666666",
			            shadow_blur:2,
			            showpercent:true,
			            column_width:"70%",
			            bar_height:"70%",
			            radius:"100%",
			            title:{
			                  text:"资源类型比例分布",
			                  color:"#111111",
			                  fontsize:20,
			                  font:"微软雅黑",
			                  textAlign:"center",
			                  height:30,
			                  offsetx:0,
			                  offsety:0
			            },
			            subtitle:{
			                  text:"",
			                  color:"#111111",
			                  fontsize:16,
			                  font:"微软雅黑",
			                  textAlign:"center",
			                  height:20,
			                  offsetx:0,
			                  offsety:0
			            },
			            footnote:{
			                  text:"",
			                  color:"#111111",
			                  fontsize:12,
			                  font:"微软雅黑",
			                  textAlign:"right",
			                  height:20,
			                  offsetx:0,
			                  offsety:0
			            },
			            legend:{
			                  enable:false,
			                  background_color:"rgb(238,238,238)",
			                  color:"#333333",
			                  fontsize:12,
			                  border:{
			                        color:"#BCBCBC",
			                        width:0
			                  },
			                  column:1,
			                  align:"right",
			                  valign:"center",
			                  offsetx:0,
			                  offsety:0
			            },
			            coordinate:{
			                  width:"80%",
			                  height:"84%",
			                  background_color:"#ffffff",
			                  axis:{
			                        color:"#a5acb8",
			                        width:[1,"",1,""]
			                  },
			                  grid_color:"#d9d9d9",
			                  label:{
			                        fontweight:500,
			                        color:"#666666",
			                        fontsize:11
			                  }
			            },
			            label:{
			                  fontweight:500,
			                  color:"#666666",
			                  fontsize:11
			            },
			            type:"pie2d",
			            data:$scope.stuffTypeCountData
			      });
			      chart.draw();
			
			});
	     
});